
name = "nihility"
license = "MIT"
licenselink = "https://github.com/nobarudo/nihility/blob/master/LICENSE"
description = ""
homepage = "https://github.com/nobarudo/nihility"
tags = ["blog"]
features = []
min_version = "0.41"

[author]
  name = "nobarudo"
  homepage = ""
